quarkus:
  http:
    port: 8080
    host: localhost
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:./target/output/myDb;create=true
  hibernate-orm:
    log:
      sql: true
    database:
      generation: update
